### ISSUE TITLE
Uhåndert feil - connection problem mot PDL

### ISSUE THREAD

**Issue by albrektsson** [navikt/omsorgspenger-sak#100]
java.lang.IllegalStateException: Feil vid hent av data fra PDL:
	at no.nav.omsorgspenger.sak.HentIdentPdlMediator.hentIdentitetsnummer$omsorgspenger_sak(HentIdentPdlMediator.kt:30)
	at no.nav.omsorgspenger.sak.HentIdentPdlMediator$hentIdentitetsnummer$1.invokeSuspend(HentIdentPdlMediator.kt)

Caused by: kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getReceiveException(AbstractChannel.kt:1141)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:938)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpClose(AbstractChannel.kt:343)
	at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:272)
	at kotlinx.coroutines.channels.ChannelCoroutine.close(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:94)
	at io.ktor.network.tls.TLSClientHandshake$input$1.invokeSuspend(TLSClientHandshake.kt:92)

**Comment by albrektsson** [comment]
Fikset (?) i #319
